// Generated by scripts/templates/import-rve.ts; do not edit.
import C0 from './imported/animated-list';
import C1 from './imported/animated-text';
import C2 from './imported/area-chart';
import C3 from './imported/blinds-transition';
import C4 from './imported/bokeh-circles';
import C5 from './imported/bounce-text';
import C6 from './imported/bubble-pop-text';
import C7 from './imported/camera-shake';
import C8 from './imported/card-flip';
import C9 from './imported/chapter-title';
import C10 from './imported/chart-animation';
import C11 from './imported/cinematic-title-intro';
import C12 from './imported/circular-progress';
import C13 from './imported/clock-wipe';
import C14 from './imported/comparison-chart';
import C15 from './imported/countdown-intro';
import C16 from './imported/countdown-timer';
import C17 from './imported/credits-roll';
import C18 from './imported/cross-dissolve';
import C19 from './imported/donut-chart';
import C20 from './imported/end-card';
import C21 from './imported/fade-through-black';
import C22 from './imported/film-burn';
import C23 from './imported/floating-bubble-text';
import C24 from './imported/gallery-grid';
import C25 from './imported/geometric-patterns';
import C26 from './imported/glitch-text';
import C27 from './imported/gradient-shift';
import C28 from './imported/grid-pulse';
import C29 from './imported/image-carousel';
import C30 from './imported/image-comparison-slider';
import C31 from './imported/image-zoom-reveal';
import C32 from './imported/iris-transition';
import C33 from './imported/ken-burns';
import C34 from './imported/letterbox-reveal';
import C35 from './imported/line-chart';
import C36 from './imported/liquid-wave';
import C37 from './imported/logo-blur-reveal';
import C38 from './imported/logo-bounce-drop';
import C39 from './imported/logo-fade-reveal';
import C40 from './imported/logo-glitch-reveal';
import C41 from './imported/logo-scale-rotate';
import C42 from './imported/logo-spin-reveal';
import C43 from './imported/logo-split-reveal';
import C44 from './imported/logo-stroke-draw';
import C45 from './imported/logo-typewriter';
import C46 from './imported/lower-third';
import C47 from './imported/masonry-gallery';
import C48 from './imported/matrix-rain';
import C49 from './imported/morph-transition';
import C50 from './imported/noise-grain';
import C51 from './imported/notification-pop';
import C52 from './imported/parallax-pan';
import C53 from './imported/particle-explosion';
import C54 from './imported/photo-stack';
import C55 from './imported/picture-in-picture';
import C56 from './imported/pie-chart';
import C57 from './imported/pixel-transition';
import C58 from './imported/polaroid-frame';
import C59 from './imported/popping-text';
import C60 from './imported/progress-bars';
import C61 from './imported/progress-steps';
import C62 from './imported/pulsing-text';
import C63 from './imported/push-transition';
import C64 from './imported/quote-card';
import C65 from './imported/rotating-carousel';
import C66 from './imported/slide-text';
import C67 from './imported/slide-wipe';
import C68 from './imported/sound-wave';
import C69 from './imported/split-screen';
import C70 from './imported/spotlight-reveal';
import C71 from './imported/starfield';
import C72 from './imported/stat-counter';
import C73 from './imported/subscribe-reminder';
import C74 from './imported/text-highlight';
import C75 from './imported/title-split';
import C76 from './imported/typewriter-subtitle';
import C77 from './imported/vignette-pulse';
import C78 from './imported/whip-pan';
import C79 from './imported/zoom-pulse';
import C80 from './imported/zoom-through';
export const registry = {"rve_animated_list": {component: C0, media: false},
"rve_animated_text": {component: C1, media: false},
"rve_area_chart": {component: C2, media: false},
"rve_blinds_transition": {component: C3, media: false},
"rve_bokeh_circles": {component: C4, media: false},
"rve_bounce_text": {component: C5, media: false},
"rve_bubble_pop_text": {component: C6, media: false},
"rve_camera_shake": {component: C7, media: false},
"rve_card_flip": {component: C8, media: false},
"rve_chapter_title": {component: C9, media: false},
"rve_chart_animation": {component: C10, media: false},
"rve_cinematic_title_intro": {component: C11, media: false},
"rve_circular_progress": {component: C12, media: false},
"rve_clock_wipe": {component: C13, media: false},
"rve_comparison_chart": {component: C14, media: false},
"rve_countdown_intro": {component: C15, media: false},
"rve_countdown_timer": {component: C16, media: false},
"rve_credits_roll": {component: C17, media: false},
"rve_cross_dissolve": {component: C18, media: false},
"rve_donut_chart": {component: C19, media: false},
"rve_end_card": {component: C20, media: false},
"rve_fade_through_black": {component: C21, media: false},
"rve_film_burn": {component: C22, media: false},
"rve_floating_bubble_text": {component: C23, media: false},
"rve_gallery_grid": {component: C24, media: false},
"rve_geometric_patterns": {component: C25, media: false},
"rve_glitch_text": {component: C26, media: false},
"rve_gradient_shift": {component: C27, media: false},
"rve_grid_pulse": {component: C28, media: false},
"rve_image_carousel": {component: C29, media: false},
"rve_image_comparison_slider": {component: C30, media: false},
"rve_image_zoom_reveal": {component: C31, media: false},
"rve_iris_transition": {component: C32, media: false},
"rve_ken_burns": {component: C33, media: true},
"rve_letterbox_reveal": {component: C34, media: false},
"rve_line_chart": {component: C35, media: false},
"rve_liquid_wave": {component: C36, media: false},
"rve_logo_blur_reveal": {component: C37, media: false},
"rve_logo_bounce_drop": {component: C38, media: false},
"rve_logo_fade_reveal": {component: C39, media: false},
"rve_logo_glitch_reveal": {component: C40, media: false},
"rve_logo_scale_rotate": {component: C41, media: false},
"rve_logo_spin_reveal": {component: C42, media: false},
"rve_logo_split_reveal": {component: C43, media: false},
"rve_logo_stroke_draw": {component: C44, media: false},
"rve_logo_typewriter": {component: C45, media: false},
"rve_lower_third": {component: C46, media: false},
"rve_masonry_gallery": {component: C47, media: false},
"rve_matrix_rain": {component: C48, media: false},
"rve_morph_transition": {component: C49, media: false},
"rve_noise_grain": {component: C50, media: false},
"rve_notification_pop": {component: C51, media: false},
"rve_parallax_pan": {component: C52, media: true},
"rve_particle_explosion": {component: C53, media: false},
"rve_photo_stack": {component: C54, media: false},
"rve_picture_in_picture": {component: C55, media: false},
"rve_pie_chart": {component: C56, media: false},
"rve_pixel_transition": {component: C57, media: false},
"rve_polaroid_frame": {component: C58, media: false},
"rve_popping_text": {component: C59, media: false},
"rve_progress_bars": {component: C60, media: false},
"rve_progress_steps": {component: C61, media: false},
"rve_pulsing_text": {component: C62, media: false},
"rve_push_transition": {component: C63, media: false},
"rve_quote_card": {component: C64, media: false},
"rve_rotating_carousel": {component: C65, media: false},
"rve_slide_text": {component: C66, media: false},
"rve_slide_wipe": {component: C67, media: false},
"rve_sound_wave": {component: C68, media: false},
"rve_split_screen": {component: C69, media: false},
"rve_spotlight_reveal": {component: C70, media: false},
"rve_starfield": {component: C71, media: false},
"rve_stat_counter": {component: C72, media: false},
"rve_subscribe_reminder": {component: C73, media: false},
"rve_text_highlight": {component: C74, media: false},
"rve_title_split": {component: C75, media: false},
"rve_typewriter_subtitle": {component: C76, media: false},
"rve_vignette_pulse": {component: C77, media: false},
"rve_whip_pan": {component: C78, media: false},
"rve_zoom_pulse": {component: C79, media: true},
"rve_zoom_through": {component: C80, media: false}};
