export function fluidLoaderOptions(compact: boolean) {
  return {
    IMMEDIATE: true,
    AUTO: true,
    INTERVAL: 6500,
    SIM_RESOLUTION: compact ? 64 : 96,
    DYE_RESOLUTION: compact ? 256 : 512,
    DENSITY_DISSIPATION: 0.15,
    VELOCITY_DISSIPATION: 0.08,
    PRESSURE: 0.8,
    PRESSURE_ITERATIONS: compact ? 12 : 16,
    CURL: 12,
    SPLAT_RADIUS: 0.28,
    SPLAT_FORCE: 1100,
    SPLAT_COUNT: 2,
    SHADING: true,
    COLORFUL: true,
    COLOR_UPDATE_SPEED: 2,
    TRANSPARENT: false,
    BACK_COLOR: { r: 8, g: 18, b: 24 },
    BLOOM: !compact,
    BLOOM_ITERATIONS: 5,
    BLOOM_RESOLUTION: 128,
    BLOOM_INTENSITY: 0.65,
    BLOOM_THRESHOLD: 0.55,
    BLOOM_SOFT_KNEE: 0.7,
    SUNRAYS: !compact,
    SUNRAYS_RESOLUTION: 96,
    SUNRAYS_WEIGHT: 0.75,
  } as const;
}
